# Generated by Django 3.2.6 on 2021-08-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('fname', models.CharField(max_length=23)),
                ('rollno', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
