# Generated by Django 3.2.6 on 2021-09-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=120)),
                ('owner', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Allotment_of_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=120)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=120)),
                ('admission_fee', models.IntegerField(blank=True, null=True)),
                ('tution_fee', models.IntegerField(blank=True, null=True)),
                ('extra_fine', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.class_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=129)),
            ],
        ),
        migrations.CreateModel(
            name='Floors_of_hostels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Room_of_hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.floors_of_hostels')),
            ],
        ),
        migrations.CreateModel(
            name='Room_type_hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=120, null=True)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.batches')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.class_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Student_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20, null=True)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.batches')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.class_registration')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.exam_type')),
            ],
        ),
        migrations.CreateModel(
            name='Student_fee_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_date', models.DateField()),
                ('applied_fee', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.class_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Student_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=80)),
                ('father_name', models.CharField(blank=True, max_length=90, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Shemale', 'Shemale'), ('Other', 'Other')], max_length=90)),
                ('D_O_B', models.DateField()),
                ('address', models.CharField(blank=True, max_length=90, null=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('nationality', models.CharField(choices=[('Pakistani', 'Pakistani'), ('Indian', 'Indian'), ('Other', 'Other')], max_length=20)),
                ('registration_no', models.IntegerField(unique=True)),
                ('cnic', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
                ('picture', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Student_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('slip_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.class_registration')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_information')),
            ],
        ),
        migrations.CreateModel(
            name='Student_record_hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.add_hostel')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_information')),
            ],
        ),
        migrations.CreateModel(
            name='Subject_of_different_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=120, null=True)),
                ('theory_marks', models.IntegerField(blank=True, null=True)),
                ('passing_marks', models.IntegerField(blank=True, null=True)),
                ('practical_marks', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='waiter',
        ),
        migrations.AddField(
            model_name='student_fee_collection',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_information'),
        ),
        migrations.AddField(
            model_name='student_exam',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_information'),
        ),
        migrations.AddField(
            model_name='student_exam',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.class_subject'),
        ),
        migrations.AddField(
            model_name='student_class',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_information'),
        ),
        migrations.AddField(
            model_name='room_of_hostel',
            name='room_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.room_type_hostel'),
        ),
        migrations.AddField(
            model_name='floors_of_hostels',
            name='hostel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_record_hostel'),
        ),
        migrations.AddField(
            model_name='class_subject',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject_of_different_classes'),
        ),
        migrations.AddField(
            model_name='allotment_of_room',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.room_of_hostel'),
        ),
        migrations.AddField(
            model_name='allotment_of_room',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_information'),
        ),
    ]
