# Generated by Django 3.2.6 on 2021-09-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210920_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_hostel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
