# Generated by Django 3.2.6 on 2021-09-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_add_hostel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floors_of_hostels',
            name='hostel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.add_hostel'),
        ),
    ]
